#!/usr/bin/env bash

build() {
	add_systemd_unit 'global-kmonad@.service'
	add_udev_rule '/etc/udev/rules.d/70-kmonad.rules'
	add_file '/etc/kmonad/personal.kbd'
	add_binary '/usr/bin/kmonad'
}

help() {
	cat <<HELPEOF
This hook allows using KMonad configurations with systemd initramfs.
Mostly useful in combination with `sd-encrypt`.
The KMonad configuration `/etc/kmonad/personal.kbd` gets applied to every keyboard.
HELPEOF
}
