vim.g.     mapleader = ' '
vim.g.maplocalleader = ','

require 'jkeDev.libext'
require 'jkeDev.vars'
require 'jkeDev.opts'
require 'jkeDev.keys'
require 'jkeDev.templates'
require 'jkeDev.plugins'
require 'jkeDev.autocmds'
